swagger: "2.0"
info:
  description: "Endpoint documentation for ensemble challenge"
  version: "1.0.0"
  title: "Ensemble Challenge"
  contact:
    email: "reyre8@gmail.com"
host: "localhost/ensemblechallenge"

tags:
- name: "order"
  description: "Handles information about orders"
schemes:
- "http"
paths:
  /orders/{id}:
    get:
      tags:
      - "order"
      summary: "Get an order by id"
      description: "Returns an order record"
      operationId: "getOrder"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of order to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Order"
        400:
          description: "Invalid id supplied"
        404:
          description: "Record not found"
  /orders:
    get:
      tags:
      - "order"
      summary: "Get all orders in the system"
      description: "Returns a list of orders"
      operationId: "getOrders"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Orders"
        400:
          description: "Business logic error"
    post:
      tags:
      - "order"
      summary: "Add a new order"
      description: ""
      operationId: "addOrder"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Order object that is going to be created"
        required: true
        schema:
          $ref: "#/definitions/OrderPost"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PostOrderResponse"
        400:
          description: "Business logic error"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      OrderCreation:
        type: "string"
        format: "date-time"
      Name:
        type: "string"
      EmailAddress:
        type: "string"
      Telephone:
        type: "string"
      Products:
        type: "array"
        items:
          type: "object"
          properties:
            Name:
              type: "string"
            Quantity:
              type: "integer"
              format: "int64"
  OrderPost:
    type: "object"
    properties:
      OrderCreation:
        type: "string"
        format: "date-time"
      Name:
        type: "string"
      EmailAddress:
        type: "string"
      Telephone:
        type: "string"
      Products:
        type: "array"
        items:
          type: "object"
          properties:
            Name:
              type: "string"
            Quantity:
              type: "integer"
              format: "int64"
  Orders:
    type: "array"
    items:
      $ref: "#/definitions/Order"
  PostOrderResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
